name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: 21
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

      - name: Check build
        run: ./gradlew publishToMavenLocal

      - name: Run JVM tests
        run: ./gradlew jvmTest

      - name: Run Android tests
        run: ./gradlew testAndroidHostTest

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Check abi
        run: ./gradlew checkLegacyAbi
